"""Evidence-backed evaluation of guided mission contracts."""

import re
from collections.abc import Iterable
from urllib.parse import urlsplit

from agentic_tester.artifacts.store import ArtifactStore
from agentic_tester.llm.base import LLMAdapter
from agentic_tester.models.evidence import Evidence, EvidenceType
from agentic_tester.models.mission import Checkpoint, ExpectedBehavior
from agentic_tester.models.observation import PageObservation
from agentic_tester.models.results import (
    CheckpointResult,
    ExpectationEvaluation,
    StepResult,
)


class OracleEngine:
    """Evaluate mission expectations using deterministic and semantic oracles.

    Network, console, and navigation assertions are resolved from browser facts.
    UI and state assertions are delegated to the configured LLM only after the
    relevant observation evidence has been assembled. Provider failures become
    ``uncertain`` results instead of being mistaken for passes.
    """

    def __init__(self, llm: LLMAdapter, artifact_store: ArtifactStore) -> None:
        self._llm = llm
        self._artifact_store = artifact_store
        self._evidence: dict[str, Evidence] = {}

    def reset(self) -> None:
        """Discard evidence from a prior mission when the engine is reused."""

        self._evidence.clear()

    def get_evidence(self) -> list[Evidence]:
        """Return all evidence generated by this oracle in insertion order."""

        return list(self._evidence.values())

    async def evaluate_expectation(
        self,
        expected: ExpectedBehavior,
        observation: PageObservation,
        recent_steps: list[StepResult] | None = None,
    ) -> ExpectationEvaluation:
        """Evaluate one expectation against the current observation."""

        recent_steps = recent_steps or []
        step_index = recent_steps[-1].step_index if recent_steps else None
        evidence = self._observation_evidence(observation, step_index)
        if expected.type == "network":
            return self._evaluate_network(expected, observation, evidence)
        if expected.type == "error_absence":
            return self._evaluate_error_absence(expected, observation, evidence)
        if expected.type == "navigation":
            return self._evaluate_navigation(expected, observation, evidence)
        return await self._evaluate_semantic(expected, observation, evidence, recent_steps)

    async def evaluate_checkpoint(
        self,
        checkpoint: Checkpoint,
        observation: PageObservation,
        recent_steps: list[StepResult] | None = None,
    ) -> CheckpointResult:
        """Evaluate all assertions attached to one explicit action checkpoint."""

        evaluations = [
            await self.evaluate_expectation(expected, observation, recent_steps)
            for expected in checkpoint.expectations
        ]
        invariant_violations = await self.check_invariants(checkpoint.invariants, observation)
        failed = any(item.verdict == "fail" for item in evaluations)
        uncertain = any(item.verdict == "uncertain" for item in evaluations)
        return CheckpointResult(
            checkpoint_description=checkpoint.description,
            passed=not failed and not uncertain and not invariant_violations,
            required=checkpoint.required,
            expectation_evaluations=evaluations,
            invariant_violations=invariant_violations,
            evidence=_unique_evidence(
                [item for evaluation in evaluations for item in self._evidence_for(evaluation)]
            ),
        )

    async def evaluate_final(
        self,
        expectations: list[ExpectedBehavior],
        observation: PageObservation,
        all_steps: list[StepResult] | None = None,
    ) -> list[ExpectationEvaluation]:
        """Evaluate final mission expectations in declaration order."""

        return [
            await self.evaluate_expectation(expected, observation, all_steps)
            for expected in expectations
        ]

    async def check_invariants(
        self,
        invariants: list[str],
        observation: PageObservation,
    ) -> list[str]:
        """Return invariant descriptions that are violated or cannot be verified."""

        violations: list[str] = []
        for invariant in invariants:
            normalized = invariant.casefold()
            if _mentions_console_cleanliness(normalized):
                if any(entry.level == "error" for entry in observation.console_entries):
                    violations.append(invariant)
                continue
            if _mentions_server_errors(normalized):
                if any(
                    entry.is_failure and (entry.status is None or entry.status >= 500)
                    for entry in observation.network_log
                ):
                    violations.append(invariant)
                continue
            if _mentions_loaded_page(normalized):
                if not observation.url or (
                    not observation.title and not observation.visible_text_summary
                ):
                    violations.append(invariant)
                continue

            expected = ExpectedBehavior(
                expectation_id=f"invariant:{len(violations)}:{invariant[:32]}",
                description=invariant,
                type="state",
                severity="must",
            )
            evaluation = await self._evaluate_semantic(
                expected,
                observation,
                self._observation_evidence(observation, None),
                [],
            )
            if evaluation.verdict != "pass":
                violations.append(invariant)
        return violations

    async def detect_anomalies(
        self,
        observation: PageObservation,
        recent_steps: list[StepResult] | None = None,
        expected_url: str | None = None,
    ) -> list[str]:
        """Extract objective anomalies observed during a prescribed mission step."""

        del recent_steps  # Retained in the API for future sequence-aware checks.
        anomalies: list[str] = []
        for console_entry in observation.console_entries:
            if console_entry.level == "error":
                anomalies.append(f"Console error: {console_entry.text}")
        for network_entry in observation.network_log:
            if network_entry.is_failure or (
                network_entry.status is not None and network_entry.status >= 400
            ):
                status = (
                    str(network_entry.status)
                    if network_entry.status is not None
                    else "network failure"
                )
                anomalies.append(
                    f"HTTP/network failure: {network_entry.method} "
                    f"{network_entry.url} ({status})"
                )
        if not observation.url or (
            not observation.title and not observation.visible_text_summary
        ):
            anomalies.append("Blank page observed: no title or visible text was captured.")
        if expected_url is not None and not _same_origin(observation.url, expected_url):
            anomalies.append(
                f"Unexpected navigation outside the mission origin: {observation.url}"
            )
        return _unique_strings(anomalies)

    def _evaluate_network(
        self,
        expected: ExpectedBehavior,
        observation: PageObservation,
        evidence: list[Evidence],
    ) -> ExpectationEvaluation:
        description = expected.description
        method_match = re.search(
            r"\b(GET|POST|PUT|PATCH|DELETE|OPTIONS|HEAD)\b",
            description,
            re.IGNORECASE,
        )
        status_match = re.search(
            r"\b(?:status|http|response|returns?|returning)\s*[:=]?\s*(\d{3})\b",
            description,
            re.IGNORECASE,
        )
        endpoint_match = re.search(
            r"(?:https?://[^\s'\"`]+|/(?:api|graphql|auth|v\d+)[^\s'\"`]*)",
            description,
            re.IGNORECASE,
        )
        method = method_match.group(1).upper() if method_match else None
        status = int(status_match.group(1)) if status_match else None
        endpoint = endpoint_match.group(0).rstrip(".,);]") if endpoint_match else None
        candidates = [
            entry
            for entry in observation.network_log
            if (method is None or entry.method.upper() == method)
            and (endpoint is None or _url_matches(entry.url, endpoint))
        ]
        if not method and not endpoint and not status:
            return self._uncertain(expected, evidence, "The network contract could not be parsed deterministically.")
        if not candidates:
            return self._evaluation(
                expected,
                "fail",
                0.95,
                f"No matching network request was observed for {description!r}.",
                evidence,
                "deterministic_network",
            )
        if status is not None:
            matching_status = [entry for entry in candidates if entry.status == status]
            if matching_status:
                return self._evaluation(
                    expected,
                    "pass",
                    1.0,
                    f"Observed the expected {method or ''} request with status {status}.",
                    evidence,
                    "deterministic_network",
                )
            observed = ", ".join(str(entry.status) for entry in candidates)
            return self._evaluation(
                expected,
                "fail",
                1.0,
                f"Matching request was observed, but status was {observed}, expected {status}.",
                evidence,
                "deterministic_network",
            )
        if any(not entry.is_failure for entry in candidates):
            return self._evaluation(
                expected,
                "pass",
                0.95,
                "A matching network request completed without a failure flag.",
                evidence,
                "deterministic_network",
            )
        return self._evaluation(
            expected,
            "fail",
            1.0,
            "The matching network request was marked as failed.",
            evidence,
            "deterministic_network",
        )

    def _evaluate_error_absence(
        self,
        expected: ExpectedBehavior,
        observation: PageObservation,
        evidence: list[Evidence],
    ) -> ExpectationEvaluation:
        errors = [entry.text for entry in observation.console_entries if entry.level == "error"]
        if not errors:
            return self._evaluation(
                expected,
                "pass",
                1.0,
                "No browser console errors were observed in the captured interval.",
                evidence,
                "deterministic_console",
            )
        return self._evaluation(
            expected,
            "fail",
            1.0,
            f"Observed {len(errors)} browser console error(s): {'; '.join(errors[:3])}",
            evidence,
            "deterministic_console",
        )

    def _evaluate_navigation(
        self,
        expected: ExpectedBehavior,
        observation: PageObservation,
        evidence: list[Evidence],
    ) -> ExpectationEvaluation:
        target = _navigation_target(expected.description)
        if target is None:
            return self._uncertain(expected, evidence, "The navigation target could not be parsed deterministically.")
        if _url_matches(observation.url, target):
            return self._evaluation(
                expected,
                "pass",
                1.0,
                f"The current URL matches the expected navigation target {target!r}.",
                evidence,
                "deterministic_navigation",
            )
        return self._evaluation(
            expected,
            "fail",
            1.0,
            f"Current URL is {observation.url!r}; expected it to match {target!r}.",
            evidence,
            "deterministic_navigation",
        )

    async def _evaluate_semantic(
        self,
        expected: ExpectedBehavior,
        observation: PageObservation,
        evidence: list[Evidence],
        recent_steps: list[StepResult],
    ) -> ExpectationEvaluation:
        del recent_steps
        try:
            verdict = await self._llm.evaluate_behavior(observation, expected, evidence)
        except Exception as exc:  # noqa: BLE001  # Provider failures are uncertainty, not passes.
            return self._uncertain(
                expected,
                evidence,
                f"Semantic oracle unavailable: {type(exc).__name__}: {exc}",
            )
        valid_ids = {item.evidence_id for item in evidence}
        evidence_ids = [item for item in verdict.evidence_ids if item in valid_ids]
        if not evidence_ids:
            evidence_ids = [item.evidence_id for item in evidence]
        return ExpectationEvaluation(
            expectation_id=expected.expectation_id,
            description=expected.description,
            severity=expected.severity,
            verdict=verdict.verdict,
            confidence=verdict.confidence,
            explanation=verdict.explanation,
            evidence_ids=evidence_ids,
            evaluator_type="llm_semantic",
        )

    def _observation_evidence(
        self,
        observation: PageObservation,
        step_index: int | None,
    ) -> list[Evidence]:
        evidence = [
            self._register(
                self._artifact_store.create_evidence(
                    EvidenceType.SCREENSHOT,
                    "oracle",
                    step_index,
                    artifact_path=observation.screenshot_path,
                    url=observation.url,
                )
            ),
            self._register(
                self._artifact_store.create_evidence(
                    EvidenceType.ACCESSIBILITY,
                    "oracle",
                    step_index,
                    excerpt=observation.accessibility_tree[:2_000],
                )
            ),
            self._register(
                self._artifact_store.create_evidence(
                    EvidenceType.URL,
                    "oracle",
                    step_index,
                    excerpt=observation.url,
                    url=observation.url,
                )
            ),
            self._register(
                self._artifact_store.create_evidence(
                    EvidenceType.TEXT,
                    "oracle",
                    step_index,
                    excerpt=observation.visible_text_summary[:2_000],
                )
            ),
        ]
        for console_entry in observation.console_entries:
            evidence.append(
                self._register(
                    self._artifact_store.create_evidence(
                        EvidenceType.CONSOLE,
                        "oracle",
                        step_index,
                        excerpt=console_entry.text,
                        level=console_entry.level,
                    )
                )
            )
        for network_entry in observation.network_log:
            evidence.append(
                self._register(
                    self._artifact_store.create_evidence(
                        EvidenceType.NETWORK,
                        "oracle",
                        step_index,
                        excerpt=f"{network_entry.method} {network_entry.url}",
                        **network_entry.model_dump(mode="json"),
                    )
                )
            )
        return evidence

    def _register(self, evidence: Evidence) -> Evidence:
        self._evidence[evidence.evidence_id] = evidence
        return evidence

    def _evidence_for(self, evaluation: ExpectationEvaluation) -> list[Evidence]:
        return [self._evidence[item] for item in evaluation.evidence_ids if item in self._evidence]

    @staticmethod
    def _evaluation(
        expected: ExpectedBehavior,
        verdict: str,
        confidence: float,
        explanation: str,
        evidence: list[Evidence],
        evaluator_type: str,
    ) -> ExpectationEvaluation:
        return ExpectationEvaluation(
            expectation_id=expected.expectation_id,
            description=expected.description,
            severity=expected.severity,
            verdict=verdict,
            confidence=confidence,
            explanation=explanation,
            evidence_ids=[item.evidence_id for item in evidence],
            evaluator_type=evaluator_type,
        )

    @staticmethod
    def _uncertain(
        expected: ExpectedBehavior,
        evidence: list[Evidence],
        explanation: str,
    ) -> ExpectationEvaluation:
        return ExpectationEvaluation(
            expectation_id=expected.expectation_id,
            description=expected.description,
            severity=expected.severity,
            verdict="uncertain",
            confidence=0.0,
            explanation=explanation,
            evidence_ids=[item.evidence_id for item in evidence],
            evaluator_type="oracle_uncertain",
        )


def _url_matches(url: str, target: str) -> bool:
    normalized_url = url.rstrip("/").casefold()
    normalized_target = target.rstrip("/").casefold()
    if normalized_target.startswith(("http://", "https://")):
        return normalized_url == normalized_target or normalized_url.startswith(f"{normalized_target}?")
    return normalized_target in normalized_url


def _same_origin(left: str, right: str) -> bool:
    left_parts = urlsplit(left)
    right_parts = urlsplit(right)
    return (
        left_parts.scheme.casefold(),
        left_parts.hostname.casefold() if left_parts.hostname else None,
        left_parts.port,
    ) == (
        right_parts.scheme.casefold(),
        right_parts.hostname.casefold() if right_parts.hostname else None,
        right_parts.port,
    )


def _navigation_target(description: str) -> str | None:
    match = re.search(
        r"(?:to|at|contains?|equals?)\s+([\w./?=&:#%-]+)",
        description,
        re.IGNORECASE,
    )
    if match:
        return match.group(1).rstrip(".,);]")
    path = re.search(r"(?:https?://[^\s'\"`]+|/[A-Za-z0-9._~:/?#\[\]@!$&'()*+,;=%-]+)", description)
    return path.group(0).rstrip(".,);]") if path else None


def _mentions_console_cleanliness(value: str) -> bool:
    return "console" in value and any(word in value for word in ("no ", "without", "zero", "no error"))


def _mentions_server_errors(value: str) -> bool:
    return "5xx" in value or "500" in value or "server error" in value


def _mentions_loaded_page(value: str) -> bool:
    return any(phrase in value for phrase in ("page loaded", "page is loaded", "not blank", "not be blank"))


def _unique_strings(values: Iterable[str]) -> list[str]:
    return list(dict.fromkeys(values))


def _unique_evidence(values: Iterable[Evidence]) -> list[Evidence]:
    seen: set[str] = set()
    unique: list[Evidence] = []
    for value in values:
        if value.evidence_id not in seen:
            seen.add(value.evidence_id)
            unique.append(value)
    return unique
